### ISSUE TITLE
[BUG] Unexpected Behavior for Seamster Spawn

### ISSUE THREAD

**Issue by csmrookie** [Rotwood-Vale/Ratwood-Keep#1257]
## Describe the bug
Whenever I spawn in as a Seamster, I seem to get into the weirdest fucking places- instead of what should usually be a spawn for a seamster, like his workshop or the docks.

## Round ID: 
Sword1066-00.50.29

## Steps to Reproduce:
Try and spawn in as a Seamster, and watch what happens.

## Additional context
Here's a screenshot. 
![Screenshot 2024-10-24 221246](https://github.com/user-attachments/assets/af6f9b46-efef-4bae-be55-1df2f2106d45)
This is me, the Seamster in a Manor with my head decapitated from a goblin ambush and carrying the vampire lord's sword, Crimson Fang.

**Comment by Nakalon** [comment]
What in the holy fuck.

This is cursed.

I have never had this happen to me and I've been testing seamster daily for days...

Maybe its something new, I'll try on a new branch.

**Comment by Nakalon** [comment]
![image](https://github.com/user-attachments/assets/a38627b2-bfbc-4b58-a17d-c1468eacc3d6)

Could not replicate this on local...

**Comment by Nakalon** [comment]
Could you tell me how many times this happened and what were the other places you spawned in?

**Comment by Nakalon** [comment]
Also please check if you had the "wild night" special!
That will make you spawn randomly in the bog!

**Comment by Nakalon** [comment]
> > Also please check if you had the "wild night" special! That will make you spawn randomly in the bog!
> 
> tossing this to you since seamsteresses...ess... clothes maker. is things you are working on

Doing my best to track this, however it seems to only happen on the live server. Just this round it happened.
I need more info....

**Comment by csmrookie** [comment]
I didn't have the Wild Night Special trait that round, but Coin Counter. Want me to play again as Seamster to check if it's true?

If so, I hope I spawn in the king's room, so it'll be an awkward beginning between me, the king and his wife.

**Comment by csmrookie** [comment]
So joined up on the current, and I got some photos to show.
![Screenshot 2024-10-25 175356](https://github.com/user-attachments/assets/32f9dd47-ac81-4074-a83e-424748370ec1)
![Screenshot 2024-10-25 180312](https://github.com/user-attachments/assets/a6b7691b-e45c-4d6a-9cd5-8cace94a7122)

**Comment by Nakalon** [comment]
This is caused by #1248 
Finally found it!

**Comment by csmrookie** [comment]
So were all good?

**Comment by Nakalon** [comment]
> So were all good?

We're good, love!
