### ISSUE TITLE
[BUG] Legendary arcanists can't scry

### ISSUE THREAD

**Issue by Azlier** [Rotwood-Vale/Ratwood-Keep#1402]
## Describe the bug

Old court mages, starting with legendary Arcane skill, cannot use the scrying orb. It shatters in-hand on 100% of attempts regardless of target or timing. Mages with master or higher aren't supposed to be able to shatter the orb at all on the first attempt, and legendary skill is supposed to completely prevent shattering in 100% of attempts regardless of timing.

## Round ID:

Zard1136-00.47.09

## Steps to Reproduce:

1. Be old
2. Be court magician
3. Attempt to scry someone
4. Fail to scry; only cry

## Additional context

This doesn't apply to mages with skill less than legendary, it seems, who can still scry as expected.

**Comment by Nakalon** [comment]
Strange. Probably my fault. Will look into it.
