### ISSUE TITLE
[BUG] grabbing yourself sets a permanent offset

### ISSUE THREAD

**Issue by wow50000** [Rotwood-Vale/Ratwood-Keep#1476]
## Describe the bug
the offset from grabbing yourself doesnt reset when you let go

## Round ID:
![image](https://github.com/user-attachments/assets/6b5cc348-a56a-4eb8-ae98-4a81cfdf9100)

## Steps to Reproduce:
grab yourself

**Comment by TheFenix323** [comment]
Can't seem to reproduce this in local, may have been fixed by #1506

**Comment by wow50000** [comment]
yeah it seems to be fixed
