### ISSUE TITLE
[BUG] Cheesecake platter sprite issue + some other cooking issues.

### ISSUE THREAD

**Issue by Keazra** [Rotwood-Vale/Ratwood-Keep#1477]
## Describe the bug

When I put a cooked cheesecake slice on a platter, the sprite disappears! It still exists and is edible, but it just disappears. I'm unsure if this happens for other items or just the cheesecake.

## Round ID:

![image](https://github.com/user-attachments/assets/b1f66a62-0c14-486b-bcee-77a50e4adba1)

## Steps to Reproduce:

As described already!

**Comment by Keazra** [comment]
![image](https://github.com/user-attachments/assets/c73c3e57-74be-4787-b3e2-6f1e09744ec7)

Buttered toast has the same issue. As does combining two fried cackleberries.

**Comment by Keazra** [comment]
Hmn. I don't know what happened, but I was cooking some fried cackleberries, and I think the hearth ran out of fuel - and now I can't use it any longer..

![image](https://github.com/user-attachments/assets/f9fe429d-eb36-4a21-822b-b902a6b477f8)

In the above picture, I'm inspecting the floor tile of the pan/hearth/egg.

**Comment by Nakalon** [comment]
> ![image](https://private-user-images.githubusercontent.com/38389279/383864037-c73c3e57-74be-4787-b3e2-6f1e09744ec7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMjAyMTksIm5iZiI6MTczMTExOTkxOSwicGF0aCI6Ii8zODM4OTI3OS8zODM4NjQwMzctYzczYzNlNTctNzRiZS00Nzg3LWIzZTItNmYxZTA5NzQ0ZWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDAyMzgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkOGUyZDQ1ZGFhNjI4NWE3M2U2ODUyNjJjNTEwOWE4NmE0ZmFjMDFlZWZhNTE1MDk5NDI0OTE1N2NiMDFmNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BtNQhZm1wWVNBUwIVjjvR5lk5betGsTTcU0xejjknuI)
> 
> Buttered toast has the same issue. As does combining two fried cackleberries.

This i can probably fix.
Tell me the exact names of the items that appear invisible!

**Comment by Keazra** [comment]
Those are the names, buttered toast and fried cackleberries.

**Comment by Nakalon** [comment]
Sorry I forgot about this
