### ISSUE TITLE
[BUG] Wooden forks don't have a sprite

### ISSUE THREAD

**Issue by john-pawson** [Rotwood-Vale/Ratwood-Keep#1492]
## Describe the bug

Well, easy as it's said. Wooden forks don't have a sprite, and it's not on the icon file. I've searched other repos too and they don't have it either so it's not so easily fixed.

## Steps to Reproduce:

1. Get a wooden fork
2. Realize you cannot see it

## Additional context

Unless someone else is able to find the sprite on a repo i didn't check, or is able to make their own fork icon, i've replaced it with a placeholder here: https://github.com/Rotwood-Vale/Ratwood-Keep/pull/1490 But it should truly get properly fixed if possible, don't want it staying like this forever. But i'm no spriter to make the new icon myself.

**Comment by Nakalon** [comment]
How long has this been like this?

**Comment by john-pawson** [comment]
> How long has this been like this?

Probably since the alloys port that brought most of the other sprite problems too, since it's the only one that actually changes anything with the fork sprites. So 6 days from now.

**Comment by Eriripng** [comment]
you are safe now my child
