### ISSUE TITLE
[BUG] Unexpected Behavior for Bows and Arrows, they don't work

### ISSUE THREAD

**Issue by TonyKarsh** [Rotwood-Vale/Ratwood-Keep#1504]
## Describe the bug
When I try to nock an arrow into my bow, it just hits the bow with the arrow. This happens whether I'm nocking an arrow by hand or by clicking the bow on the quiver.

## Round ID:
Forest1175-04.26.59

## Steps to Reproduce:
Grab a bow and arrow, try to put the arrow into the bow. Or grab a bow and quiver of arrows, and try to click the bow on the quiver to nock an arrow.

## Additional context
Is probably related to test merged PR #1479 Artificer Expansion Pack: Contraptions

**Comment by TonyKarsh** [comment]
I didn't see the comments on discord saying it's fixed and will be fine whenever the test merge updates until just now. Looks like that was 10 hours ago though, so, hopefully the test merge updates soon, or it might be still broken.

**Comment by Nakalon** [comment]
yeah sorry, IDK how test merges update very well and I don't control them, but they should be fixed!

**Comment by Nakalon** [comment]
OHHHHH YOU MEAN THE BOW

**Comment by Nakalon** [comment]
I need to find another solution for this I only solved quivers becuase that was the info I got

**Comment by Nakalon** [comment]
Regaining object flags while I try to figure out another solution

**Comment by Nakalon** [comment]
This is fixed! Hopefuly when the TM updates you wont have any more issues! Closing!
