### ISSUE TITLE
[BUG] Duke's lack of Belongings

### ISSUE THREAD

**Issue by Brutishcrab51** [Rotwood-Vale/Ratwood-Keep#1572]
## Describe the bug

The Duke spawns with Black Boots, the Master Rod, the Crown, a Shirt and the Duke's Jacket. As I understand it, he's also meant to spawn with a Coin Purse and a Belt. He doesn't now. This is related to the new clothing update.

## Round ID:

N/A.

## Steps to Reproduce:

Play the role 'Duke'.

## Additional context

N/A.

**Comment by john-pawson** [comment]
Was fixed on https://github.com/Rotwood-Vale/Ratwood-Keep/pull/1553/ I believe, third commit.
