### ISSUE TITLE
[BUG] Sword despawned when stuck into a familiar that then dies.

### ISSUE THREAD

**Issue by DabTheBold** [Rotwood-Vale/Ratwood-Keep#1600]
Issue reported from  Round ID: 1228 (Ratwood Keep [18+ Only] - Apply on Discord!)

Reporting client version: 514.1589

I fought a familiar with my rapier that the Fablefield Goliard gets. My rapier stuck in the spirit wolf familiar right before it died. Then with its corpse the sword also vanished.

**Comment by ScienceMom** [comment]
I can ATTEMPT to fix this, it should be as simple as forcing a familiar to eject any embedded objects upon death in the same way that arrows can automatically eject from an embed over time.
