### ISSUE TITLE
[BUG] Invisible Dish - Wiener and Onions

### ISSUE THREAD

**Issue by Lord-Preston** [Rotwood-Vale/Ratwood-Keep#1612]
## Describe the bug

When you make the dish wiener and onions using a fried sausage on fried onions you will make the dish, but it will be invisible.

![Invisible wiener and onions 1](https://github.com/user-attachments/assets/2a89a920-3192-4df0-a091-76ab017390df)

![Invisible wiener and onions 2](https://github.com/user-attachments/assets/ffa7466f-02f6-42f2-bc81-c7d98a7512de)

## Round ID:

![Round ID](https://github.com/user-attachments/assets/1c419430-be5f-4c08-b564-a4064ba76cea)

## Steps to Reproduce:

1. Fry onions on a frying pan, place the fried onions on a table. 
2. Fry a sausage on a frying pan, and then use it on the fried onions on the table. 
3. Once completed nothing will appear on the table, but if you alt + RMB the table you can see that the dish is there.

## Additional context

You can interact with the dish and eat it. The spirit is simply missing/invisible.

**Comment by Nakalon** [comment]
What a surprise...
