### ISSUE TITLE
[BUG] Fishyy

### ISSUE THREAD

**Issue by notafurryy** [Rotwood-Vale/Ratwood-Keep#1621]
## Describe the bug

Minor spelling mistake: https://github.com/Rotwood-Vale/Ratwood-Keep/blob/3bb85b3720ed26cdbb3cabe5eb26743b7b62dbce/code/modules/spells/roguetown/acolyte/sawbones.dm#L545

## Steps to Reproduce:

Make fish syrum and look at it while having treatment skill

## Additional context

![image](https://github.com/user-attachments/assets/201a11e5-5bd0-4bce-8382-fe7915ecbd11)

**Comment by Eriripng** [comment]
![image](https://github.com/user-attachments/assets/29882a78-21a3-4601-9f7a-d008fd724ddc)
