### ISSUE TITLE
[REQUEST] Give grenzel mercs guns

### ISSUE THREAD

**Issue by notafurryy** [Rotwood-Vale/Ratwood-Keep#1633]
## Is your feature request related to a problem? Please describe. 

nope

## Describe the solution you'd like

Give grenzels mercs dueling pistols and arquebus as rare subclasses the like of the bandit hedgeknight

Oh also with that a class system for mercenaries would be neat, giving them more varied equipment wise and letting the player choose it, like picking a loadout for bandits/subclass for adventurers.

## Describe alternatives you've considered

nope again

## Additional context

Grenzel mercenaries are based on Landsknecht and Doppelsöldner mercenaries, they were equipped with pikes and swords which is represented in game but historically the latter were often if not always also seen carrying firearms mainly the arquebus. I think adding a firearm for a tiny amount of supposed elite mercenaries would not cause /too/ much of an issue balance wise while also being thematically accurate.

**Comment by Coolgat3** [comment]
> The arquebusiers in the Event were Grenzel flavored. Not sure where arquebuses were developed in the in the official lore atm, but I'd like to think and have heard that they're a Grenzel invention (or were at least popularized by them). Someone would have to correct me though.

I thought we literally stole them
