### ISSUE TITLE
[BUG] Werewolf Infection not working

### ISSUE THREAD

**Issue by Gyrandola** [Rotwood-Vale/Ratwood-Keep#174]
## Describe the bug

Self explanatory.

## Steps to Reproduce:

Be a werewolf, bite someone over and over.

## Additional context

100% caused by [THE ONLY CURE ](https://github.com/Blackstone-SS13/BLACKSTONE/pull/1260)

**Comment by Drayco84** [comment]
If STDs ever get added, lycanthropy needs to be one of them.
