### ISSUE TITLE
[BUG] Henchmen cannot latejoin

### ISSUE THREAD

**Issue by Makximus** [Rotwood-Vale/Ratwood-Keep#1959]

**Comment by JagOfTroy** [comment]
![Screenshot 2024-12-18 144510](https://github.com/user-attachments/assets/92eda98f-f252-4f1d-bf0f-c6349132ebc3)
Was able to reproduce this issue. Henchmen is not available for latejoin after checking this on private server with no one else after round started.

**Comment by Kevak** [comment]
Fixed here

[https://github.com/Rotwood-Vale/Ratwood-Keep/pull/1989]

**Comment by Makximus** [comment]
> Fixed here
> 
> [PR 1989](https://github.com/Rotwood-Vale/Ratwood-Keep/pull/1989l)

This just takes me to a 404 error, what happened there?
