### ISSUE TITLE
[BUG] Sprites are broken

### ISSUE THREAD

**Issue by TheFenix323** [Rotwood-Vale/Ratwood-Keep#307]
## Describe the bug
Certain sprites that where working correctly now are looking wrong on female characters, been happening since a few rounds by now.

## Steps to Reproduce:
Pick as a female character a job with a dress (for example shophand) and you will see the sprite in the preview.

## Additional context

![Captura](https://github.com/Rotwood-Vale/Ratwood-Keep/assets/64550272/db8e58a5-c12f-4cbb-9af9-00d5f3fea3df)
![Proof2](https://github.com/Rotwood-Vale/Ratwood-Keep/assets/64550272/b94b282d-8bca-4ea2-b30e-cff6975f8d4a)
![proof1](https://github.com/Rotwood-Vale/Ratwood-Keep/assets/64550272/1088382f-1827-4854-85a2-38f26730ff9a)
![Prooof3](https://github.com/Rotwood-Vale/Ratwood-Keep/assets/64550272/45f17af7-db1c-4612-86d3-0f66e8dd563a)

**Comment by CalamaBanana** [comment]
![image](https://github.com/Rotwood-Vale/Ratwood-Keep/assets/46299792/40171505-a045-4315-82ac-e40a7cead18d)
As comparison, how the shophand dress is supposed to look like. To me it seems the game is putting the male dress shape on women now, instead of the female version.
