### ISSUE TITLE
[BUG] Freshly turned vampyres start BANED sometimes and can not regenerate because of it.

### ISSUE THREAD

**Issue by CalamaBanana** [Rotwood-Vale/Ratwood-Keep#371]
I was a clerk with standard clerk equipment. Nothing holy, nothing silver. I was turned during daylight, and started burning the second I was turned and ran into shadows. I was not able to use regenerate because I was baned from the beginning.

What I do suspect: I handled silver coins while I was alive, a long time before I was turned. But I did not have any silver coins in any pocket after I was turned.

Edit:
Looking through the code myself a little, it seems you are only supposed to get BANED if you get stabbed by a silver dagger? Silver just stops you from picking up things otherwise. I have no clue where and why I had that status effect on me. No one stabbed me with a silver dagger. 

And it is supposed to last only 5 seconds in the first place, not the entire round. Something is wonky there, can't tell where.

**Comment by Useroth** [comment]
Should be resolved in https://github.com/Rotwood-Vale/Ratwood-Keep/pull/515
