### ISSUE TITLE
[BUG] My BANE is not letting me REGEN!

### ISSUE THREAD

**Issue by Murkyyyy** [Rotwood-Vale/Ratwood-Keep#378]
## Describe the bug

Well iv just been turned into a vamp, i neither have a cross nor anything on me that causes it but the pop up 'My BANE is not letting me REGEN!' keeps popping up. Iv tried taking off everything on me and doing it but it still pops up or even using the regen fountain but the issue persists. This has happened before on an entirely different character and they suffered the same issue with not even the regen pond doing anything.

## Round ID:

Jewel1269-00.16.45

## Steps to Reproduce:

I have no idea at this point. Both times i was a kobold so maybe that? The first time i did walk outside without a disguise and got burnt but the second(aka most recent) time i didn't even leave the room i was turned in and i still cant do anything

**Comment by Useroth** [comment]
Should be resolved in #515
