### ISSUE TITLE
[BUG] Missing dwarf grenzelhoft sprites

### ISSUE THREAD

**Issue by Teragenic** [Rotwood-Vale/Ratwood-Keep#433]
Missing grenzelhoftian dwarf sprite

![image](https://github.com/user-attachments/assets/d3ba4aa2-7919-49c4-9184-eeb674182461)

**Comment by Teragenic** [comment]
Female

**Comment by Teragenic** [comment]
Male works apparently?

**Comment by Teragenic** [comment]
Thank Cre. It's been fixed. The sprites are in asset-donation.

**Comment by Alanii** [comment]
> Male works apparently?

Male has the curriass in the dmi. That is why.

**Comment by Teragenic** [comment]
Fixed. Thank you Cre.
