### ISSUE TITLE
[BUG] When a mask is taken off, and put into the belt slot, it still blocks the mouth

### ISSUE THREAD

**Issue by Hmeister-real** [Rotwood-Vale/Ratwood-Keep#534]
## Describe the bug

It shouldnt, but if you put it on your belt it still blocks the mouth

## Steps to Reproduce:

Take mask from face onto belt, still cant drink, sorcery

**Comment by Squird5** [comment]
Also makes you bald

![ratwood_helm bug 1](https://github.com/user-attachments/assets/84e11d62-ab0a-448a-b364-98930de81bc8)
![ratwood_helm bug 2](https://github.com/user-attachments/assets/9a1c6f4e-4a02-42d3-9350-30440ce7eeae)

**Comment by Hmeister-real** [comment]
This is still a big issue, with masks and other armors that can go in the belt slots (you cannot sleep with armor in the belt slot either now so it's more of an issue than before)
