### ISSUE TITLE
[BUG] The pate recipe makes descaled kobold tail instead of pate

### ISSUE THREAD

**Issue by Vanaim** [Rotwood-Vale/Ratwood-Keep#819]
> /datum/crafting_recipe/roguetown/cooking/pate
	name = "pate"
	reqs = list(
		/obj/item/organ/liver = 1,
		/obj/item/reagent_containers/food/snacks/rogue/onionslice = 2,
		/obj/item/reagent_containers/food/snacks/rogue/meat/mince = 1
		)
	tools = list(/obj/item/rogueweapon/huntingknife)
	result = /obj/item/reagent_containers/food/snacks/rogue/meat/koboldtail
	craftdiff = 2
	subtype_reqs = TRUE
	req_table = TRUE

**Comment by DeerJesus** [comment]
i curse myself for copying and pasting from other items as a template. ill fix this tomorrow im kinda sick rn

**Comment by Vanaim** [comment]
And where?
![images](https://github.com/user-attachments/assets/aa01632e-58bf-49dd-ac9b-2db956a7a0b7)
