### ISSUE TITLE
[BUG] scrying orb doesnt work on people with symbols in their name in their name

### ISSUE THREAD

**Issue by K4rlox** [Rotwood-Vale/Ratwood-Keep#959]
## Describe the bug
as the title says, if someone has a name like
Jester 'Powderpuff'
they cant be scried

## Steps to Reproduce:
be wizar
get orb
right click heart
choose someone with a ' in their name
copy paste
"i dont know anyone by that name"

**Comment by Eriripng** [comment]
taking a look on this

![image](https://github.com/user-attachments/assets/d9766386-dca8-4fc5-bf4f-f267dec06592)

**Comment by Eriripng** [comment]
you are safe now my child
